Create new mutect2ConsensusTumorOnly
oicr-gsi/mutect2ConsensusTumorOnly pull request #1
Opened 2024-05-30 01:43 UTC by gavin-peng

When trying to add tumor only mode to mutect2Consensus, wdl syntax issue for optional value still not solved. 
After much effort removed scatter to adress optional array from collecting scatter can not indexing its elememts ( and resulting a lot of repeating and renaming), the work in progress is in: https://github.com/oicr-gsi/mutect2Consensus/blob/gavin_updates/mutect2Consensus.wdl
then other place with optional nested struct again can not access its fields, and report error:
Failed to process workflow definition 'mutect2Consensus' (reason 1 of 2): Failed to process 'call mutect2.mutect2 as sscsScMatchedMutect2' (reason 1 of 2): Failed to process expression 'normalInputGroup_.sscsScBamAndIndex.bam' (reason 1 of 1): No such field 'sscsScBamAndIndex' on type WomCompositeType {
 dcsScBamAndIndex -> WomCompositeType {
 bam -> File
bamIndex -> File 
}
sscsScBamAndIndex -> WomCompositeType {
 bam -> File
bamIndex -> File 
}
allUniqueBamAndIndex -> WomCompositeType {
 bam -> File
bamIndex -> File 
} 
}?
Failed to process workflow definition 'mutect2Consensus' (reason 2 of 2): Failed to process 'call mutect2.mutect2 as sscsScMatchedMutect2' (reason 2 of 2): Failed to process expression 'normalInputGroup_.sscsScBamAndIndex.bamIndex' (reason 1 of 1): No such field 'sscsScBamAndIndex' on type WomCompositeType {
 dcsScBamAndIndex -> WomCompositeType {
 bam -> File
bamIndex -> File 
}
sscsScBamAndIndex -> WomCompositeType {
 bam -> File
bamIndex -> File 
}
allUniqueBamAndIndex -> WomCompositeType {
 bam -> File
bamIndex -> File 
} 
}?

This shows even after use select_first to try to convert it to non-optional, wdl still treat it as optional.

So I am creating another repo to write the tumor only mode for the wdl.

2024-05-30 15:39 UTC, pruzanov approved these changes

2024-06-05 17:24 UTC, bibilujan commented
Gavin can you update the summary on the read me, it still makes reference to the normal.

2024-06-05 17:24 UTC, bibilujan requested changes
summary update

2024-06-06 16:18 UTC, gavin-peng commented
updated readme

2024-06-06 18:13 UTC, bibilujan approved these changes

2024-06-07 18:52 UTC, merged